# Generated by Django 5.1.6 on 2025-03-05 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customeruser_personneluser_provideruser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Active'), (4, 'Completed')], default=0, verbose_name='Status User')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('duration_months', models.IntegerField(verbose_name='Term Months')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Start At')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='accounts.customeruser', verbose_name='Personnel User')),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=20, verbose_name='Payment Number')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Principal Amount')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Interest Amount')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Payment')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remaining Balance')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan', verbose_name='Loan')),
            ],
            options={
                'verbose_name': 'Amortization Schedule',
                'verbose_name_plural': 'Amortization Schedules',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='LoanFundType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Amount')),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interest Rate')),
                ('min_duration_months', models.PositiveSmallIntegerField(verbose_name='Min Duration Months')),
                ('max_duration_months', models.PositiveIntegerField(verbose_name='Max Duration Months')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_fund_types', to='accounts.personneluser', verbose_name='Personnel User')),
            ],
            options={
                'verbose_name': 'Loan Fund Type',
                'verbose_name_plural': 'Loan Fund Types',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='LoanFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_funds', to='accounts.provideruser', verbose_name='Provider User')),
                ('loan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanfundtype', verbose_name='Loan Type')),
            ],
            options={
                'verbose_name': 'Loan Fund',
                'verbose_name_plural': 'Loan Funds',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Amount')),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interest Rate')),
                ('min_duration_months', models.PositiveSmallIntegerField(verbose_name='Min Duration Months')),
                ('max_duration_months', models.PositiveIntegerField(verbose_name='Max Duration Months')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_types', to='accounts.personneluser', verbose_name='Personnel User')),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loantype', verbose_name='Loan Type'),
        ),
    ]
