# Generated by Django 5.1.6 on 2025-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('-create_at', '-update_at'), 'verbose_name': 'Loan', 'verbose_name_plural': 'Loan'},
        ),
    ]
