# Generated by Django 5.1.6 on 2025-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='duration_months',
            field=models.PositiveIntegerField(null=True, verbose_name='Term Months'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(verbose_name='Term Months'),
        ),
    ]
