# Generated by Django 5.1.6 on 2025-03-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanfund_duration_months_alter_loan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationschedule',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='amortizationschedule',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.loan', verbose_name='Loan'),
        ),
    ]
