# Generated by Django 5.1.6 on 2025-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_amortizationschedule_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationschedule',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
    ]
