# Generated by Django 5.1.6 on 2025-03-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_amortizationschedule_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizationschedule',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='loans.loan', verbose_name='Loan'),
        ),
    ]
